// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	ENVIRONMENT: "production";
	AUTH_SECRET: "supersecret";
	DB: D1Database;
	ASSETS: Fetcher;
}
